### ISSUE TITLE
맞춤법이 틀렸습니다. 

### ISSUE THREAD

**Issue by wnduqrla** [Choi-Jinwoo/dgsw.cs#2]
접근 한정자로 수식하지 않은 클래스의 **멥버는** 무조건 private 로 접근 수준이 자동으로 지정됨 (X)

접근 한정자로 수식하지 않은 클래스의 **멤버는** 무조건 private 로 접근 수준이 자동으로 지정됨 (O)

**Comment by Choi-Jinwoo** [comment]
수정 완료
